### ISSUE TITLE
Integration with Piped

### ISSUE THREAD

**Issue by kzar79** [teticio/deej-ai.online-app#5]
Impressive work, compliments! The only problem I see is that it is dependant to Spotify.

Do you think it would be complex to play songs using [Piped](https://github.com/TeamPiped/Piped) instead? (or better, make an option in the settings to choose which service to use) 

If you can point the places in the code that need to be changed I could try to do it.

**Comment by teticio** [comment]
Thank you. Yes, it could be done. I have wanted to keep it simple, but you could make a fork and host a Piped version. I don't know the platform... Apart from cosmetic things like changing the names and removing the Spotify API stuff from the React app, the main job would be to pre-compute the vectors for all the tracks. A potential issue is that you would probably only be able to calculate the "mp3tovec" embeddings (which correspond to creativity=1) and not the "track2vec" embeddings (creativity=0), because these require information about what tracks tend to go together in playlists (I guess you can't get this from Piped). I did do something like this for Bandcamp as a private project, although it was an earlier, cruder iteration of the app. The place to look for preparing the embeddings is in the `train` directory.

The next main work would be to adapt the playlist widgets to play the Piped mp3s and display the cover art. As Spotify provides a preview URL, I use this (`spotify_urls.p` - created in the last step of the `train` procedure). You would have to replace these with an appropriate URL (could be a blob I guess). In the `backend/main.py` file you will find where the cover art is injected into the Spotify playlist widget. I basically took a snapshot of the widget as one day it suddenly stopped working because they changed it on their end. You might prefer to write your own playlist widget in JS.

**Comment by kzar79** [comment]
Thank you for your reply. 

I was actually thinking of something easier. Recomputing the mp3 vectors would be quite a long and heavy thing, and I don't think it would be feasible given the huge amount of music youtube contains.

So I was thinking of a way to just adapt the playlist widget to find and play the songs with Piped instead of Spotify (or as you suggest, write a new playlist widget).

I could just add an option in the settings "Use Piped / Use Spotify" to change the widget used, and make a Pull request when everything works.

What I was wondering is how the playlist widget finds the songs on Spotify.

Or, better, how the whole playlist thing works. I looked at the code but there are a lot of different playlist components (Playlist, RemovablePlaylist, SelectedPlaylist, ShowPlaylist, ...) so I don't even know where to start and what needs to be cloned/adapted. If you could please shortly describe how it works, it would be of great help.

So essentially the idea is to use everything as is, and "just" play the songs with Piped. That is, after the songs are selected and everything is ready, instead of asking Spotify to play them, find them with Piped and play them with it.

The problem I see is that with Piped there are 2 ways to find a song/video: A. by its videoId (youtube id); B. with a query (e.g. song title + artist + album). 
Problem with method A is that there is no existing database to convert a spotify song id to youtube id.
Problem with method B is that it returns a lot of possible results. How to select automatically the best? There could be remixes, covers... Some people proposed this method but I am skeptical (https://github.com/dwickstrom/tuba , https://github.com/valeriangalliat/spotify-to-youtube , https://medium.com/pythoneers/from-spotify-to-youtube-music-how-i-wrote-a-simple-tool-in-python-to-migrate-my-playlists-705e878a7cf0 ...)

Anyway, I plan to use method B and see if it is acceptable. Remains the problem of "where in the code".

**Comment by teticio** [comment]
Ah I see. I hadn't appreciated that it was an interface to Youtube. In that case, the main problem is mapping from Spotify to Youtube. I think there are some things around that attempt to do this but you could try with searches, fuzzy matching and heuristics. Might be messy though. I don't really know how Piped works or what it does but, supposing you have a database mapped of all the songs to Youtube equivalents - how would you get the mp3? Would you have to download it from Youtube (I know this is possible but dodgy)?

If you wanted to try to do the mapping, I could pass you the database of all the (1M) tracks currently in deej-ai.online (IDs, track name, author and URL of mp3 preview).

**Comment by teticio** [comment]
Now you mention it, I remember writing this post some time ago that might help, even though it is talking about going in the opposite direction. https://medium.com/@teticio/migrate-your-mp3-library-to-spotify-201155d92273

**Comment by teticio** [comment]
If you do try to do this (following any of the above approaches), you will probably need to do some web scraping tricks as you will almost certainly get blocked / throtled.

**Comment by kzar79** [comment]
No, in fact I do not plan to download mp3s from youtube or actually do the mapping.

What I'd like to do is just to change how songs are played. That is, write a new playlist widget that, given the song title, artist and album, just searches the "best match" on youtube and plays it with Piped.

I know (kind of) how to do it with Piped APIs, I just don't know where to write changes in your code (and how your code works). I could read all of your code, but if you could point me the right places, it would be much easier.

Project for another life: download the mp3s and playlists from youtube and recreate the vectors.

**Comment by teticio** [comment]
Got it. In that case, I would implement the searching algorithm in the `backend/main.py` and rewrite the `src/components/Playlist.js` to display your alternative widget.

**Comment by kzar79** [comment]
So all the other components are not used to play the songs? Only Playlist.js? That's great. Except that, from what I understand, it is just a wrapper of the original Spotify widget, which gets a list of ids and does everything. So I will have to write from scratch all the functioning (display the list, buttons to play, pause, skip...). I will try.

**Comment by teticio** [comment]
Exactly. I didn't want to ave to write my own playlist widget when Spotify's one did the trick. You might be able to adapt the existing one more easily than starting from scratch. The JS in the `public` directory, but it is is gzipped. Or you could get a widget from the public domain. I just wanted to keep the Spotify aesthetic, as the app is linked to Spotify.
